stages:
  - lint
  - build
  - test

checkbadchars:
  stage: lint
  script: >
    test $(grep -caxv '.*' *.f *.f90 *.h  README* |
    cut -d: -f2 | awk '{ SUM += $1} END { print SUM }') -eq 0

enforce_unixish:
  stage: lint
  script: test $(file -k  *.f *.f90 *.h | grep -c "CRLF") -eq 0

build:centos7:
  stage: build
  image: garrettwrong/spec_centos-7
  script:
  - make CC=gfortran xspec
  artifacts:
    paths:
    - xspec
    expire_in: 1 week

case1:
  stage: test
  image: garrettwrong/spec_centos-7
  script:
  - cd ci/G1V03L2Fi
  - ../../xspec G1V03L2Fi.001.sp
  #- comparison
  artifacts:
    when: always
    paths:
    - ci/G1V03L2Fi/G1V03L2Fi.001.sp.h5
    expire_in: 1 week
  dependencies:
  - build:centos7

