SPEC: src/bfield.f90 File Reference
bfield.f90 File Reference
Returns \(\dot s \equiv B^s / B^\zeta\) and \(\dot \theta \equiv B^\theta / B^\zeta\).
Functions/Subroutines
subroutine bfield (zeta, st, Bst)
Compute the magnetic field.
subroutine bfield_tangent (zeta, st, Bst)
compute the tangential magnetic field
Detailed Description
Returns \(\dot s \equiv B^s / B^\zeta\) and \(\dot \theta \equiv B^\theta / B^\zeta\).
Function/Subroutine Documentation
bfield_tangent()
subroutine bfield_tangent (real, intent(in) zeta, real, dimension(1:6), intent(in) st, real, dimension(1:6), intent(out) Bst)
compute the tangential magnetic field
Parameters
[in] zeta toroidal angle
[in] st radial(s) and poloidal(theta) positions
[out] Bst tangential magnetic field
References allglobal::ate, allglobal::ato, allglobal::aze, allglobal::azo, bfield(), allglobal::cpus, allglobal::gbzeta, get_cheby_d2(), get_zernike_d2(), constants::half, allglobal::halfmm, allglobal::im, allglobal::in, allglobal::ivol, allglobal::lcoordinatesingularity, inputlist::lrad, allglobal::mn, allglobal::mpi_comm_spec, inputlist::mpol, allglobal::mvol, allglobal::myid, allglobal::ncpu, allglobal::node, allglobal::notstellsym, constants::one, fileunits::ounit, allglobal::regumm, numerical::small, constants::two, numerical::vsmall, inputlist::wmacros, and constants::zero.