SPEC: src/dfp100.f90 File Reference
dfp100.f90 File Reference
Split the work between MPI nodes and evaluate the global constraint.
Functions/Subroutines
subroutine dfp100 (Ndofgl, x, Fvec, LComputeDerivatives)
Split the work between MPI nodes and evaluate the global constraint.
Detailed Description
Split the work between MPI nodes and evaluate the global constraint.
Function/Subroutine Documentation
dfp100()
subroutine dfp100 (integer Ndofgl, real, dimension(1:mvol-1) x, real, dimension(1:ndofgl) Fvec, logical LComputeDerivatives)
Split the work between MPI nodes and evaluate the global constraint.
Parameters
Ndofgl
x
Fvec
LComputeDerivatives
References allocate_beltrami_matrices(), allocate_geometry_matrices(), compute_guvijsave(), allglobal::cpus, curent(), inputlist::curpol, allglobal::dbdx, allglobal::ddttcc, allglobal::ddttcs, allglobal::ddttsc, allglobal::ddttss, allglobal::ddtzcc, allglobal::ddtzcs, allglobal::ddtzsc, allglobal::ddtzss, allglobal::ddzzcc, allglobal::ddzzcs, allglobal::ddzzsc, allglobal::ddzzss, deallocate_beltrami_matrices(), deallocate_geometry_matrices(), dfp100(), allglobal::dma, allglobal::dmb, allglobal::dmd, allglobal::dmg, allglobal::dpflux, allglobal::dtoocc, allglobal::dtoocs, allglobal::dtoosc, allglobal::dtooss, allglobal::guvijsave, constants::half, allglobal::iconstraintok, inputlist::igeometry, allglobal::imagneticok, allglobal::in, intghs_workspace_destroy(), intghs_workspace_init(), allglobal::ipdtdpf, allglobal::iquad, allglobal::ismyvolume(), allglobal::ismyvolumevalue, inputlist::isurf, allglobal::izbs, inputlist::lconstraint, allglobal::lcoordinatesingularity, inputlist::lfreebound, allglobal::liluprecond, allglobal::localconstraint, allglobal::lplasmaregion, inputlist::lrad, allglobal::lsavedguvij, allglobal::lvacuumregion, ma00aa(), ma02aa(), matrix(), allglobal::mbpsi, allglobal::mn, allglobal::mpi_comm_spec, constants::mu0, allglobal::mvol, allglobal::myid, allglobal::nadof, allglobal::ncpu, allglobal::notmatrixfree, allglobal::nt, inputlist::nvol, allglobal::nz, constants::one, fileunits::ounit, constants::pi, constants::pi2, allglobal::solution, spsint(), spsmat(), allglobal::tdstcc, allglobal::tdstcs, allglobal::tdstsc, allglobal::tdstss, allglobal::tdszcc, allglobal::tdszcs, allglobal::tdszsc, allglobal::tdszss, allglobal::ttsscc, allglobal::ttsscs, allglobal::ttsssc, allglobal::ttssss, constants::two, volume(), allglobal::whichcpuid(), inputlist::wmacros, allglobal::xoffset, and constants::zero.
Referenced by dforce(), dfp100(), and evaluate_dmupfdx().