SPEC: Parallelization
Parallelization
Functions/Subroutines
subroutine brcast (lvol)
Broadcasts Beltrami fields, profiles, . . .
Detailed Description
Function/Subroutine Documentation
brcast()
subroutine brcast (integer, intent(in) lvol)
Broadcasts Beltrami fields, profiles, . . .
broadcasting
The construction of the Beltrami fields is distributed on separate cpus.
All "local" information needs to be broadcast so that the "global" force vector,
\begin{eqnarray} {\bf F}_i \equiv [[p+B^2/2]]_i = (p+B^2/2)_{v,i} - (p+B^2/2)_{v-1,i} \end{eqnarray}
can be constructed, and so that restart and output files can be saved to file.
Parameters
[in] lvol index of nested volume
References allglobal::ate, allglobal::ato, allglobal::aze, allglobal::azo, allglobal::bemn, allglobal::bomn, brcast(), allglobal::cpus, inputlist::curpol, inputlist::curtor, allglobal::dbbdmp, allglobal::denergydrr, allglobal::denergydzr, allglobal::dffdrz, allglobal::diotadxup, allglobal::ditgpdxtp, allglobal::dmupfdx, allglobal::dpflux, allglobal::dtflux, inputlist::helicity, allglobal::iemn, allglobal::imagneticok, allglobal::iomn, allglobal::ismyvolume(), allglobal::ismyvolumevalue, allglobal::labintegral, allglobal::lbbintegral, inputlist::lconstraint, inputlist::lfindzero, allglobal::lgdof, allglobal::lhessian3dallocated, allglobal::lhessianallocated, allglobal::localconstraint, inputlist::lrad, allglobal::mn, inputlist::mnvol, allglobal::mpi_comm_spec, inputlist::mu, allglobal::mvol, allglobal::myid, allglobal::ncpu, allglobal::notstellsym, allglobal::ntz, inputlist::nvol, fileunits::ounit, allglobal::pemn, allglobal::pomn, allglobal::semn, allglobal::somn, allglobal::vvolume, inputlist::wmacros, and constants::zero.
Referenced by brcast(), dforce(), and final_diagnostics().