SPEC: Smooth boundary
Smooth boundary
Functions/Subroutines
subroutine wa00aa (iwa00aa)
Constructs smooth approximation to wall.
subroutine vacuumphi (Nconstraints, rho, fvec, iflag)
Compute vacuum magnetic scalar potential (?)
Detailed Description
Function/Subroutine Documentation
wa00aa()
subroutine wa00aa (integer iwa00aa)
Constructs smooth approximation to wall.
solution of Laplace's equation in two-dimensions
The wall is given by a discrete set of points.
The points must go anti-clockwise.
References laplaces::alpha, laplaces::cc, allglobal::cpus, laplaces::dorm, laplaces::exterior, fileunits::gunit, constants::half, laplaces::iangle, laplaces::ic, laplaces::icint, allglobal::im, allglobal::in, allglobal::irbc, allglobal::irbs, allglobal::izbc, allglobal::izbs, allglobal::lcoordinatesingularity, allglobal::mn, inputlist::mpol, allglobal::mvol, allglobal::myid, allglobal::ncpu, laplaces::nintervals, laplaces::niterations, laplaces::np1, laplaces::np4, laplaces::nsegments, allglobal::nt, inputlist::ntor, allglobal::ntz, inputlist::nvol, allglobal::nz, inputlist::odetol, constants::one, laplaces::originalalpha, fileunits::ounit, laplaces::phi, laplaces::phid, constants::pi2, allglobal::rij, laplaces::rmid, laplaces::stage1, constants::ten, vacuumphi(), numerical::vsmall, wa00aa(), inputlist::wmacros, laplaces::xpoly, allglobal::yesstellsym, laplaces::ypoly, constants::zero, and allglobal::zij.
Referenced by vacuumphi(), and wa00aa().
vacuumphi()
subroutine vacuumphi (integer Nconstraints, real, dimension(1:nconstraints) rho, real, dimension(1:nconstraints) fvec, integer iflag)
Compute vacuum magnetic scalar potential (?)
Parameters
Nconstraints
rho
fvec
iflag
References laplaces::alpha, laplaces::cc, allglobal::cpus, laplaces::dorm, laplaces::exterior, constants::half, laplaces::iangle, laplaces::ic, laplaces::icint, allglobal::myid, allglobal::ncpu, laplaces::nintervals, laplaces::niterations, laplaces::np1, laplaces::np4, laplaces::nsegments, allglobal::ntz, constants::one, laplaces::originalalpha, fileunits::ounit, laplaces::phi, laplaces::phid, constants::pi2, allglobal::rij, laplaces::rmid, laplaces::stage1, wa00aa(), inputlist::wmacros, laplaces::xpoly, laplaces::ypoly, constants::zero, and allglobal::zij.
Referenced by wa00aa().