SPEC: src/intghs.f90 File Reference
intghs.f90 File Reference
Calculates volume integrals of Chebyshev-polynomials and covariant field for Hessian computation.
Data Types
type intghs_module::intghs_workspace
This calculates the integral of something related to matrix-vector-multiplication.
Functions/Subroutines
subroutine intghs (lquad, mn, lvol, lrad, idx)
Calculates volume integrals of Chebyshev polynomials and covariant field products.
subroutine intghs_workspace_init (lvol)
init workspace
subroutine intghs_workspace_destroy ()
free workspace.
Variables
type(intghs_workspace) intghs_module::wk
This is an instance of the intghs_workspace type.
Detailed Description
Calculates volume integrals of Chebyshev-polynomials and covariant field for Hessian computation.
Function/Subroutine Documentation
intghs()
subroutine intghs (integer, intent(in) lquad, integer, intent(in) mn, integer, intent(in) lvol, integer, intent(in) lrad, integer, intent(in) idx)
Calculates volume integrals of Chebyshev polynomials and covariant field products.
Parameters
lquad
mn
lvol
lrad
idx
References allglobal::ate, allglobal::ato, allglobal::aze, allglobal::azo, compute_guvijsave(), allglobal::cpus, allglobal::dbdx, allglobal::dtc, allglobal::dts, allglobal::dzc, allglobal::dzs, allglobal::gaussianabscissae, allglobal::gaussianweight, get_cheby(), get_zernike(), allglobal::guvij, allglobal::guvijsave, constants::half, allglobal::im, allglobal::in, intghs(), allglobal::lcoordinatesingularity, allglobal::lsavedguvij, allglobal::mne, allglobal::mpi_comm_spec, inputlist::mpol, allglobal::mvol, allglobal::myid, allglobal::ncpu, allglobal::notstellsym, allglobal::nt, allglobal::ntz, allglobal::nz, constants::one, fileunits::ounit, constants::pi, constants::pi2, allglobal::pi2pi2nfp, allglobal::pi2pi2nfphalf, allglobal::sg, numerical::small, numerical::sqrtmachprec, allglobal::tsc, allglobal::tss, allglobal::ttc, allglobal::tts, constants::two, allglobal::tzc, allglobal::tzs, numerical::vsmall, inputlist::wmacros, allglobal::yesstellsym, and constants::zero.
Referenced by get_perturbed_solution(), intghs(), intghs_workspace_destroy(), intghs_workspace_init(), matvec(), and mp00ac().
intghs_workspace_init()
subroutine intghs_workspace_init (integer, intent(in) lvol)
init workspace
Parameters
lvol
References allglobal::cpus, intghs(), allglobal::iquad, inputlist::lrad, allglobal::mn, allglobal::mpi_comm_spec, inputlist::mpol, allglobal::myid, allglobal::ncpu, allglobal::ntz, fileunits::ounit, inputlist::wmacros, and constants::zero.
Referenced by dfp100(), dfp200(), and evaluate_dmupfdx().