SPEC: lbpol.f90 File Reference
lbpol.f90 File Reference
Computes \(B_{\theta,e,0,0}\) at the interface.
Functions/Subroutines
subroutine lbpol (lvol, Bt00, ideriv, iocons)
Detailed Description
Computes \(B_{\theta,e,0,0}\) at the interface.
Parameters
[in] lvol
[in,out] Bt00
[in] ideriv
[in] iocons
Function/Subroutine Documentation
lbpol()
subroutine lbpol (integer, intent(in) lvol, real, dimension(1:mvol, 0:1, -1:2), intent(inout) Bt00, integer, intent(in) ideriv, integer, intent(in) iocons)
Parameters
[in] ideriv lbpol will return \(B_{\theta,e,0,0}\) (0) or its derivative with respect to the geometry (-1), mu (1) or the poloidal flux (2). \(\mbox{ideriv}\in\{-1,\ldots,2\} \)
[in] lvol Volume index. \(\mbox{lvol}\in\{1,\ldots,\mbox{Mvol}\} \)
[in] iocons \(B_{\theta,e,0,0}\) is evaluated on the inner (iocons=0) or outer (iocons=1) volume boundary. \(\mbox{iocons}\in\{0,1\} \)
[in,out] bt00 \(B_{\theta,e,0,0}\), with indices Bt00(lvol, iocons, ideriv).
Computes \(B_{\theta,e,0,0}\) at the volume interfaces. This is used by dfp100 to evaluate the toroidal current at the volume interfaces, and by dfp200 to construct the force gradient when the current constraint (Lconstraint=3) is used. This is also used by xspech to compute the toroidal current at the volume interfaces, written in the output.
Call coords() to compute the metric coefficients and the jacobian.
Build coefficients efmn, ofmn, cfmn, sfmn from the field vector potential Ate, Ato, Aze and Azo, and radial derivatives of the polynomial basis TT(ll,innout,1). These variables are the derivatives with respect to s of the magnetic field vector potential in Fourier space. If ideriv \(\neq 0\), construct the relevant derivatives of the vector potential.
Take the inverse Fourier transform of efmn, ofmn, cfmn, sfmn. These are the covariant components of \(\frac{\partial A}{\partial s}\), i.e. the contravariant components of \(\mathbf{B}\).
Build covariant components of the field using the metric coefficients guvij and the jacobian sg.
If ideriv=-1 (derivatives with respect to the geometry), need to add derivatives relative to the metric elements
Get derivatives of metric element by calling coords()
Compute vector potential without taking any derivatives
Add to \(\frac{\partial B_\theta}{\partial x_i}\) the contributions from \(\frac{\partial}{\partial x_i} \frac{g_{\mu\nu}}{\sqrt{g}} \)
Fourier transform the field and store it in the variables efmn, ofmn, cfmn and sfmn.
Save first even fourier mode into Bt00(lvol, iocons, ideriv)
References allglobal::ate, allglobal::ato, allglobal::aze, allglobal::azo, allglobal::cfmn, allglobal::comn, coords(), allglobal::cpus, allglobal::dbdx, allglobal::efmn, allglobal::evmn, allglobal::guvij, constants::half, inputlist::igeometry, allglobal::im, allglobal::ime, allglobal::in, allglobal::ine, invfft(), inputlist::lcheck, allglobal::lcoordinatesingularity, inputlist::lrad, allglobal::mn, allglobal::mne, constants::mu0, allglobal::mvol, allglobal::myid, allglobal::notstellsym, allglobal::nt, allglobal::ntz, allglobal::nz, allglobal::odmn, allglobal::ofmn, constants::one, fileunits::ounit, constants::pi, constants::pi2, allglobal::regumm, allglobal::sfmn, allglobal::sg, allglobal::simn, tfft(), allglobal::tt, constants::two, allglobal::yesstellsym, and constants::zero.
Referenced by dfp100(), evaluate_dmupfdx(), and xspech().