SPEC: src/memory.f90 File Reference
memory.f90 File Reference
memory management module
Functions/Subroutines
subroutine allocate_beltrami_matrices (vvol, LcomputeDerivatives)
allocate Beltrami matrices
subroutine deallocate_beltrami_matrices (LcomputeDerivatives)
deallocate Beltrami matrices
subroutine allocate_geometry_matrices (vvol, LcomputeDerivatives)
allocate geometry matrices
subroutine deallocate_geometry_matrices (LcomputeDerivatives)
deallocate geometry matrices
Detailed Description
memory management module
Function/Subroutine Documentation
allocate_beltrami_matrices()
subroutine allocate_beltrami_matrices (integer, intent(in) vvol, logical, intent(in) LcomputeDerivatives)
allocate Beltrami matrices
Parameters
vvol
LcomputeDerivatives
References allglobal::adotx, allglobal::ddotx, allglobal::dma, allglobal::dmas, allglobal::dmb, allglobal::dmd, allglobal::dmds, allglobal::dmg, allglobal::idmas, allglobal::jdmas, allglobal::liluprecond, allglobal::mbpsi, allglobal::nadof, allglobal::ndmasmax, allglobal::notmatrixfree, allglobal::solution, and inputlist::wmacros.
Referenced by dfp100(), dfp200(), and evaluate_dmupfdx().
deallocate_beltrami_matrices()
subroutine deallocate_beltrami_matrices (logical, intent(in) LcomputeDerivatives)
deallocate Beltrami matrices
Parameters
LcomputeDerivatives
References allglobal::adotx, allglobal::ddotx, allglobal::dma, allglobal::dmas, allglobal::dmb, allglobal::dmd, allglobal::dmds, allglobal::dmg, allglobal::idmas, allglobal::jdmas, allglobal::liluprecond, allglobal::mbpsi, allglobal::notmatrixfree, allglobal::solution, and inputlist::wmacros.
Referenced by dfp100(), dfp200(), and evaluate_dmupfdx().
allocate_geometry_matrices()
subroutine allocate_geometry_matrices (integer vvol, logical, intent(in) LcomputeDerivatives)
allocate geometry matrices
Parameters
vvol
LcomputeDerivatives
References allglobal::ddttcc, allglobal::ddttcs, allglobal::ddttsc, allglobal::ddttss, allglobal::ddtzcc, allglobal::ddtzcs, allglobal::ddtzsc, allglobal::ddtzss, allglobal::ddzzcc, allglobal::ddzzcs, allglobal::ddzzsc, allglobal::ddzzss, allglobal::dtc, allglobal::dtoocc, allglobal::dtoocs, allglobal::dtoosc, allglobal::dtooss, allglobal::dts, allglobal::dzc, allglobal::dzs, allglobal::guvijsave, allglobal::iquad, allglobal::lcoordinatesingularity, inputlist::lrad, allglobal::mn, inputlist::mpol, allglobal::notstellsym, allglobal::ntz, allglobal::tdstcc, allglobal::tdstcs, allglobal::tdstsc, allglobal::tdstss, allglobal::tdszcc, allglobal::tdszcs, allglobal::tdszsc, allglobal::tdszss, allglobal::tsc, allglobal::tss, allglobal::ttc, allglobal::tts, allglobal::ttsscc, allglobal::ttsscs, allglobal::ttsssc, allglobal::ttssss, allglobal::tzc, allglobal::tzs, inputlist::wmacros, and constants::zero.
Referenced by dfp100(), dfp200(), and evaluate_dmupfdx().
deallocate_geometry_matrices()
subroutine deallocate_geometry_matrices (logical, intent(in) LcomputeDerivatives)
deallocate geometry matrices
Parameters
LcomputeDerivatives
References allglobal::ddttcc, allglobal::ddttcs, allglobal::ddttsc, allglobal::ddttss, allglobal::ddtzcc, allglobal::ddtzcs, allglobal::ddtzsc, allglobal::ddtzss, allglobal::ddzzcc, allglobal::ddzzcs, allglobal::ddzzsc, allglobal::ddzzss, allglobal::dtc, allglobal::dtoocc, allglobal::dtoocs, allglobal::dtoosc, allglobal::dtooss, allglobal::dts, allglobal::dzc, allglobal::dzs, allglobal::guvijsave, allglobal::lsavedguvij, allglobal::notstellsym, allglobal::tdstcc, allglobal::tdstcs, allglobal::tdstsc, allglobal::tdstss, allglobal::tdszcc, allglobal::tdszcs, allglobal::tdszsc, allglobal::tdszss, allglobal::tsc, allglobal::tss, allglobal::ttc, allglobal::tts, allglobal::ttsscc, allglobal::ttsscs, allglobal::ttsssc, allglobal::ttssss, allglobal::tzc, allglobal::tzs, inputlist::wmacros, and constants::zero.
Referenced by dfp100(), dfp200(), and evaluate_dmupfdx().