SPEC: src/metrix.f90 File Reference
metrix.f90 File Reference
Calculates the metric quantities, \(\sqrt g \, g^{\mu\nu}\), which are required for the energy and helicity integrals.
Functions/Subroutines
subroutine metrix (lquad, lvol)
Calculates the metric quantities, \(\sqrt g \, g^{\mu\nu}\), which are required for the energy and helicity integrals.
subroutine compute_guvijsave (lquad, vvol, ideriv, Lcurvature)
compute guvijsave
Detailed Description
Calculates the metric quantities, \(\sqrt g \, g^{\mu\nu}\), which are required for the energy and helicity integrals.
Function/Subroutine Documentation
compute_guvijsave()
subroutine compute_guvijsave (integer, intent(in) lquad, integer, intent(in) vvol, integer, intent(in) ideriv, integer, intent(in) Lcurvature)
compute guvijsave
Parameters
lquad
vvol
ideriv
Lcurvature
References coords(), allglobal::gaussianabscissae, allglobal::guvij, allglobal::guvijsave, allglobal::mn, allglobal::ntz, and allglobal::sg.
Referenced by dfp100(), intghs(), and ma00aa().