var modules =
[
    [ "Diagnostics to check the code", "group__grp__diagnostics.html", "group__grp__diagnostics" ],
    [ "Free-Boundary Computation", "group__grp__free-boundary.html", "group__grp__free-boundary" ],
    [ "Parallelization", "group__grp__parallel.html", "group__grp__parallel" ],
    [ "Geometry", "group__grp__geometry.html", "group__grp__geometry" ],
    [ "Plasma Currents", "group__grp__currents.html", "group__grp__currents" ],
    [ "\"global\" force", "group__grp__global__force.html", "group__grp__global__force" ],
    [ "Input namelists and global variables", "group__grp__global.html", "group__grp__global" ],
    [ "\"local\" force", "group__grp__local__force.html", "group__grp__local__force" ],
    [ "Integrals", "group__grp__integrals.html", "group__grp__integrals" ],
    [ "Solver/Driver", "group__grp__solver__driver.html", "group__grp__solver__driver" ],
    [ "Build matrices", "group__grp__build__matrices.html", "group__grp__build__matrices" ],
    [ "Metric quantities", "group__grp__metrics.html", "group__grp__metrics" ],
    [ "Solver for Beltrami (linear) system", "group__grp__solver.html", "group__grp__solver" ],
    [ "Force-driver", "group__grp__force__driver.html", "group__grp__force__driver" ],
    [ "Some miscellaneous numerical routines", "group__grp__numerics.html", "group__grp__numerics" ],
    [ "\"packing\" of Beltrami field solution vector", "group__grp__packing.html", "group__grp__packing" ],
    [ "Conjugate-Gradient method", "group__grp__conjugate__gradient.html", "group__grp__conjugate__gradient" ],
    [ "Initialization of the code", "group__grp__initialization.html", "group__grp__initialization" ],
    [ "Output file(s)", "group__grp__output.html", "group__grp__output" ],
    [ "Coordinate axis", "group__grp__coord__axis.html", "group__grp__coord__axis" ],
    [ "Rotational Transform", "group__grp__transform.html", "group__grp__transform" ],
    [ "Plasma volume", "group__grp__volume.html", "group__grp__volume" ],
    [ "Smooth boundary", "group__grp__smooth__boundary.html", "group__grp__smooth__boundary" ],
    [ "Enhanced resolution for metric elements", "group__grp__enh__res__metr.html", "group__grp__enh__res__metr" ],
    [ "Enhanced resolution for transformation to straight-field line angle", "group__grp__enh__res__sfl.html", "group__grp__enh__res__sfl" ],
    [ "Internal Variables", "group__grp__internal__vars.html", "group__grp__internal__vars" ]
];