SPEC: mtrxhs.f90 File Reference
mtrxhs.f90 File Reference
(build matrices) ! Constructs matrices that represent the Beltrami linear system, matrix-free.
Functions/Subroutines
subroutine mtrxhs (lvol, mn, lrad, resultA, resultD, idx)
Constructs matrices that represent the Beltrami linear system, matrix-free.
Detailed Description
(build matrices) ! Constructs matrices that represent the Beltrami linear system, matrix-free.
Function/Subroutine Documentation
mtrxhs()
subroutine mtrxhs (integer, intent(in) lvol, integer, intent(in) mn, integer, intent(in) lrad, real, dimension(0:nadof(lvol)), intent(out) resultA, real, dimension(0:nadof(lvol)), intent(out) resultD, integer, intent(in) idx)
Constructs matrices that represent the Beltrami linear system, matrix-free.
Parameters
lvol
mn
lrad
resultA
resultD
idx
References allglobal::ate, allglobal::ato, allglobal::aze, allglobal::azo, allglobal::cpus, allglobal::dbdx, allglobal::dtc, allglobal::dts, allglobal::dzc, allglobal::dzs, constants::half, allglobal::im, allglobal::in, allglobal::lcoordinatesingularity, allglobal::lma, allglobal::lmavalue, allglobal::lmb, allglobal::lmbvalue, allglobal::lmc, allglobal::lmcvalue, allglobal::lmd, allglobal::lmdvalue, allglobal::lme, allglobal::lmevalue, allglobal::lmf, allglobal::lmfvalue, allglobal::lmg, allglobal::lmgvalue, allglobal::lmh, allglobal::lmhvalue, allglobal::mpi_comm_spec, inputlist::mpol, allglobal::myid, allglobal::nadof, allglobal::ncpu, allglobal::notstellsym, constants::one, fileunits::ounit, allglobal::rtm, allglobal::rtt, numerical::small, allglobal::tsc, allglobal::tss, allglobal::tt, allglobal::ttc, allglobal::tts, constants::two, allglobal::tzc, allglobal::tzs, inputlist::wmacros, allglobal::yesstellsym, and constants::zero.
Referenced by get_perturbed_solution(), matvec(), and mp00ac().