SPEC: spsint.f90 File Reference
spsint.f90 File Reference
(integrals) ! Calculates volume integrals of Chebyshev-polynomials and metric elements for preconditioner.
Functions/Subroutines
subroutine spsint (lquad, mn, lvol, lrad)
Calculates volume integrals of Chebyshev-polynomials and metric elements for preconditioner.
Detailed Description
(integrals) ! Calculates volume integrals of Chebyshev-polynomials and metric elements for preconditioner.
Function/Subroutine Documentation
spsint()
subroutine spsint (integer, intent(in) lquad, integer, intent(in) mn, integer, intent(in) lvol, integer, intent(in) lrad)
Calculates volume integrals of Chebyshev-polynomials and metric elements for preconditioner.
Parameters
lquad
mn
lvol
lrad
References allglobal::cpus, allglobal::ddttcc, allglobal::ddttcs, allglobal::ddttsc, allglobal::ddttss, allglobal::ddtzcc, allglobal::ddtzcs, allglobal::ddtzsc, allglobal::ddtzss, allglobal::ddzzcc, allglobal::ddzzcs, allglobal::ddzzsc, allglobal::ddzzss, allglobal::dtoocc, allglobal::dtoocs, allglobal::dtoosc, allglobal::dtooss, allglobal::gaussianabscissae, allglobal::gaussianweight, get_cheby(), get_zernike(), allglobal::guvijsave, constants::half, allglobal::im, allglobal::in, allglobal::ki, allglobal::kija, allglobal::kijs, allglobal::lcoordinatesingularity, allglobal::mne, inputlist::mpol, allglobal::mvol, allglobal::myid, allglobal::ncpu, allglobal::notstellsym, allglobal::ntz, constants::one, fileunits::ounit, constants::pi, constants::pi2, allglobal::pi2pi2nfp, allglobal::pi2pi2nfphalf, allglobal::regumm, numerical::small, numerical::sqrtmachprec, allglobal::tdstcc, allglobal::tdstcs, allglobal::tdstsc, allglobal::tdstss, allglobal::tdszcc, allglobal::tdszcs, allglobal::tdszsc, allglobal::tdszss, allglobal::ttsscc, allglobal::ttsscs, allglobal::ttsssc, allglobal::ttssss, constants::two, numerical::vsmall, inputlist::wmacros, allglobal::yesstellsym, and constants::zero.
Referenced by dfp100().