SPEC: spsmat.f90 File Reference
spsmat.f90 File Reference
(build matrices) ! Constructs matrices for the precondtioner.
Functions/Subroutines
subroutine spsmat (lvol, mn, lrad)
Constructs matrices for the precondtioner.
subroutine push_back (iq, nq, NN, vA, vD, vjA, qA, qD, qjA)
push a new element at the back of the queue
subroutine clean_queue (nq, NN, qA, qD, qjA)
clean the queue
subroutine addline (nq, NN, qA, qD, qjA, ns, nrow, dMAS, dMDS, jdMAS, idMAS)
add the content from the queue to the real matrices
Detailed Description
(build matrices) ! Constructs matrices for the precondtioner.
Function/Subroutine Documentation
spsmat()
subroutine spsmat (integer, intent(in) lvol, integer, intent(in) mn, integer, intent(in) lrad)
Constructs matrices for the precondtioner.
Parameters
lvol
mn
lrad
References addline(), clean_queue(), allglobal::cpus, allglobal::dma, allglobal::dmas, allglobal::dmb, allglobal::dmd, allglobal::dmds, allglobal::dmg, allglobal::idmas, allglobal::im, allglobal::in, allglobal::jdmas, allglobal::liluprecond, inputlist::mpol, allglobal::myid, allglobal::nadof, allglobal::ncpu, allglobal::ndmas, allglobal::ndmasmax, allglobal::notstellsym, constants::one, fileunits::ounit, push_back(), numerical::small, constants::two, inputlist::wmacros, allglobal::yesstellsym, and constants::zero.
Referenced by dfp100().
push_back()
subroutine push_back (integer, intent(in) iq, integer, dimension(4), intent(inout) nq, integer, intent(in) NN, real, intent(in) vA, real, intent(in) vD, integer, intent(in) vjA, real, dimension(nn,4), intent(inout) qA, real, dimension(nn,4), intent(inout) qD, integer, dimension(nn,4), intent(inout) qjA)
push a new element at the back of the queue
Parameters
iq
nq
NN
vA
vD
vjA
qA
qD
qjA
References constants::zero.
Referenced by spsmat().
clean_queue()
subroutine clean_queue (integer, dimension(4), intent(inout) nq, integer, intent(in) NN, real, dimension(nn,4), intent(inout) qA, real, dimension(nn,4), intent(inout) qD, integer, dimension(nn,4), intent(inout) qjA)
clean the queue
Parameters
nq
NN
qA
qD
qjA
References constants::zero.
Referenced by spsmat().
addline()
subroutine addline (integer, dimension(4), intent(inout) nq, integer, intent(inout) NN, real, dimension(nn,4), intent(inout) qA, real, dimension(nn,4), intent(inout) qD, integer, dimension(nn,4), intent(inout) qjA, integer, intent(inout) ns, integer, intent(inout) nrow, real, dimension(*) dMAS, real, dimension(*) dMDS, integer, dimension(*) jdMAS, integer, dimension(*) idMAS)
add the content from the queue to the real matrices
Parameters
nq
NN
qA
qD
qjA
ns
nrow
dMAS
dMDS
jdMAS
idMAS
Referenced by spsmat().