SPEC: Some miscellaneous numerical routines
Some miscellaneous numerical routines
Functions/Subroutines
subroutine gi00ab (Mpol, Ntor, Nfp, mn, im, in)
Assign Fourier mode labels.
subroutine tfft (Nt, Nz, ijreal, ijimag, mn, im, in, efmn, ofmn, cfmn, sfmn, ifail)
Forward Fourier transform (fftw wrapper)
subroutine invfft (mn, im, in, efmn, ofmn, cfmn, sfmn, Nt, Nz, ijreal, ijimag)
Inverse Fourier transform (fftw wrapper)
subroutine gauleg (n, weight, abscis, ifail)
Gauss-Legendre weights and abscissae.
Detailed Description
Function/Subroutine Documentation
gi00ab()
subroutine gi00ab (integer, intent(in) Mpol, integer, intent(in) Ntor, integer, intent(in) Nfp, integer, intent(in) mn, integer, dimension(mn), intent(out) im, integer, dimension(mn), intent(out) in)
Assign Fourier mode labels.
This routine assigns the Fourier mode labels that converts a double-sum into a single sum; i.e., the \(m_j\) and \(n_j\) are assigned where
\begin{eqnarray} f(\theta,\zeta) & = & \sum_{n=0}^{N} f_{0,n}\cos(-n \, N_P \, \zeta) + \sum_{m=1}^{M} \sum_{n=-N}^{N} f_{m,n}\cos(m\theta-n \, N_P \, \zeta) \\ & = & \sum_j f_j \cos(m_j\theta-n_j\zeta), \label{eq:condensedFourierrepresentation_numrec} \end{eqnarray}
where \(N\equiv\,\)Ntor and \(M\equiv\,\)Mpol are given on input, and \(N_P \equiv\,\)Nfp is the field periodicity.
Referenced by allglobal::readin().
tfft()
subroutine tfft (integer Nt, integer Nz, real, dimension(1:nt*nz) ijreal, real, dimension(1:nt*nz) ijimag, integer mn, integer, dimension(1:mn) im, integer, dimension(1:mn) in, real, dimension(1:mn) efmn, real, dimension(1:mn) ofmn, real, dimension(1:mn) cfmn, real, dimension(1:mn) sfmn, integer ifail)
Forward Fourier transform (fftw wrapper)
This constructs the "forward" Fourier transform.
Given a set of data, \((f_{i},g_{i})\) for \(i = 1, \dots N_\theta N_\zeta\), on a regular two-dimensional angle grid, where \(\theta_j = 2 \pi j / N_\theta\) for \(j = 0, N_\theta-1\), and \(\zeta_k = 2 \pi k / N_\zeta \) for \(k = 0, N_\zeta -1\). The "packing" is governed by \(i = 1 + j + k N_\theta\). The "discrete" resolution is \(N_\theta \equiv\,\)Nt, \(N_\zeta \equiv\,\)Nz and Ntz \(=\) Nt \(\times\) Nz , which are set in preset() .
The Fourier harmonics consistent with Eqn. \((\ref{eq:condensedFourierrepresentation_numrec})\) are constructed. The mode identification labels appearing in Eqn. \((\ref{eq:condensedFourierrepresentation_numrec})\) are \(m_j \equiv\,\)im(j) and \(n_j \equiv\,\)in(j) , which are set in readin() via a call to gi00ab() .
Parameters
Nt
Nz
ijreal
ijimag
mn
im
in
efmn
ofmn
cfmn
sfmn
ifail
References fftw_interface::cplxin, fftw_interface::cplxout, constants::half, inputlist::nfp, fileunits::ounit, constants::pi2, allglobal::pi2nfp, fftw_interface::planf, and constants::zero.
Referenced by bnorml(), curent(), lforce(), metrix(), preset(), and wa00aa().
invfft()
subroutine invfft (integer, intent(in) mn, integer, dimension(mn), intent(in) im, integer, dimension(mn), intent(in) in, real, dimension(mn), intent(in) efmn, real, dimension(mn), intent(in) ofmn, real, dimension(mn), intent(in) cfmn, real, dimension(mn), intent(in) sfmn, integer, intent(in) Nt, integer, intent(in) Nz, real, dimension(nt*nz), intent(out) ijreal, real, dimension(nt*nz), intent(out) ijimag)
Inverse Fourier transform (fftw wrapper)
Given the Fourier harmonics, the data on a regular angular grid are constructed.
This is the inverse routine to tfft() .
Parameters
[in] mn
[in] im
[in] in
[in] efmn
[in] ofmn
[in] cfmn
[in] sfmn
[in] Nt
[in] Nz
[out] ijreal
[out] ijimag
References fftw_interface::cplxin, fftw_interface::cplxout, constants::half, inputlist::nfp, fftw_interface::planb, constants::two, and constants::zero.
Referenced by coords(), curent(), jo00aa(), lforce(), preset(), and tr00ab().
gauleg()
subroutine gauleg (integer, intent(in) n, real, dimension(n), intent(out) weight, real, dimension(n), intent(out) abscis, integer, intent(out) ifail)
Gauss-Legendre weights and abscissae.
Compute Gaussian integration weights and abscissae.
From Numerical Recipes.
Parameters
[in] n
[out] weight
[out] abscis
[out] ifail
References constants::one, constants::pi, constants::two, and constants::zero.
Referenced by preset().