#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./spec_stdout.%j
#SBATCH -e ./spec_stderr.%j
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J SPEC
# Queue (Partition):
#SBATCH --partition=general
# Number of nodes and MPI tasks per node:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#
#SBATCH --mail-type=none
#SBATCH --mail-user=<userid>@rzg.mpg.de
#
# Wall clock limit:
#SBATCH --time=04:00:00

# Run the program:
srun $@
