name: Github-Actions-CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    steps:
      checkbadchars:
        script: >
          test $(grep -caxv '.*' *.f *.f90 *.h  README* |
          cut -d: -f2 | awk '{ SUM += $1} END { print SUM }') -eq 0

      enforce_unixish:
        script: test $(file -k  *.f *.f90 *.h | grep -c "CRLF") -eq 0

  build:centos7:
    container: csmiet/testspec
    script:
    - make CC=gfortran xspec
    artifacts:
      paths:
      - xspec
      expire_in: 1 week

  stable_force_free_sheet:
    stage: test
    image: csmiet/testspec
    script:
    - source source.sh
    - cd ci/G1V03L2Fi
    - xspec G1V03L2Fi.001.sp
    - python3 -m py_spec.ci.test G1V03L2Fi.001.sp.h5 compare.h5
    #comparison python3 -m py_spec.ci.testspec f1 f2
    artifacts:
      when: always
      paths:
      - ci/G1V03L2Fi/G1V03L2Fi.001.sp.h5
      expire_in: 1 week
    dependencies:
    - build:centos7
  # reproduce:
  # docker run -v `pwd`:`pwd` -w `pwd` csmiet/testspec sh -c 'source ./source.sh;cd ci/G1V03L2Fi; xspec G1V03L2Fi.001.sp; python3 -m py_spec.ci.test G1V03L2Fi.001.sp.h5 compare.h5'

  cylindrical_many_volumes:
    stage: test
    image: csmiet/testspec
    script:
    - source source.sh
    - cd ci/G2V32L1Fi
    - xspec G2V32L1Fi.001.sp
    - python3 -m py_spec.ci.test G2V32L1Fi.001.sp.h5 compare.h5
    artifacts:
      when: always
      paths:
      - ci/G2V32L1Fi/G2V32L1Fi.001.sp.h5
      expire_in: 1 week
    dependencies:
    - build:centos7
  # reproduce:
  # docker run -v `pwd`:`pwd` -w `pwd` csmiet/testspec sh -c 'source ./source.sh; cd ci/G2V32L1Fi; xspec G2V32L1Fi.001.sp; python3 -m py_spec.ci.test G2V32L1Fi.001.sp.h5 compare.h5'

  toroidal_freeboundary_vacuum:
    stage: test
    image: csmiet/testspec
    script:
    - source source.sh
    - cd ci/toroidal_freeboundary_vacuum
    - mpirun -n 4 --allow-run-as-root xspec G3V02L0Fr.sp 
    - python3 -m py_spec.ci.test G3V02L0Fr.sp.h5 compare.h5
    artifacts:
      when: always
      paths:
      - ci/G2V32L1Fi/G2V32L1Fi.001.sp.h5
      expire_in: 1 week
    dependencies:
    - build:centos7
  # reproduce:
  # docker run -v `pwd`:`pwd` -w `pwd` csmiet/testspec sh -c 'source ./source.sh; cd ci/toroidal_freeboundary_vacuum; mpirun -n 4 --allow-run-as-root xspec G3V02L0Fr.sp; python3 -m py_spec.ci.test G3V02L0Fr.sp.h5 compare.h5'
