name: build-cmake-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: csmiet/testspec
    env:
      MACHINE: docker
      SPEC_PATH: ${{ github.workspace }}
      PYTHONPATH: ${{ github.workspace }}/Utilities/pythontools
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    steps:
      - name: checkout sources
        uses: actions/checkout@master
      - name: compile_xspec
        run: |
          pip3 install ninja cmake
          cp ${SPEC_PATH}/cmake_machines/centos7_default.json ${SPEC_PATH}/cmake_config.json
          cd ${{ github.workspace }}/build
          cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_Fortran_COMPILER=mpifort -DBLA_VENDOR=OpenBLAS -DHDF5_ROOT=/usr -DHDF5_NO_FIND_PACKAGE_CONFIG_FILE=TRUE -DHDF5_PREFER_PARALLEL=TRUE .. -GNinja --prefix=${SPEC_PATH}/install
          cmake --build .
          cmake --install .
      - name: run_fast_cartesian
        run: |
          cd ${SPEC_PATH}/ci/G1V03L2Fi
          echo ${PYTHONPATH}
          mpiexec -n 3 --allow-run-as-root ${SPEC_PATH}/install/bin/xspec G1V03L2Fi.001.sp
          python3 -m py_spec.ci.test compare.h5 G1V03L2Fi.001.sp.h5 
      - name: run_fast_cylinder
        run: |
          cd ${SPEC_PATH}/ci/G2V32L1Fi
          echo ${PYTHONPATH}
          mpiexec -n 2 --allow-run-as-root ${SPEC_PATH}/install/bin/xspec G2V32L1Fi.001.sp
          python3 -m py_spec.ci.test compare.h5 G2V32L1Fi.001.sp.h5 
      - name: toroidal_freeboundary_vacuum
        run: |
          cd ${SPEC_PATH}/ci/toroidal_freeboundary_vacuum
          mpiexec -n 3 --allow-run-as-root ${SPEC_PATH}/install/bin/xspec G3V02L0Fr_LU.sp 
          mpiexec -n 3 --allow-run-as-root ${SPEC_PATH}/xspec G3V02L0Fr.sp 
          python3 -m py_spec.ci.test compare.h5 G3V02L0Fr_LU.sp.h5 --tol 1e-11
          python3 -m py_spec.ci.test compare.h5 G3V02L0Fr.sp.h5 --tol 1e-11
      - name: current_constraint_fixed_boundary
        run: |
          cd ${SPEC_PATH}/ci/G3V08L3Fi
          mpiexec -n 3 --allow-run-as-root ${SPEC_PATH}/install/bin/xspec G3V08L3Fi.001.sp
          python3 -m py_spec.ci.test compare.h5 G3V08L3Fi.001.sp.h5 --tol 1e-10
      - name: current_constraint_free_boundary
        run: |
          cd ${SPEC_PATH}/ci/G3V08L3Fr
          mpiexec -n 3 --allow-run-as-root ${SPEC_PATH}/install/bin/xspec G3V08L3Fr.001.sp
          python3 -m py_spec.ci.test compare.h5 G3V08L3Fr.001.sp.h5 --tol 1e-10



