name: build-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: csmiet/testspec
    env:
      MACHINE: docker
      SPEC_PATH: ${{ github.workspace }}
      PYTHONPATH: ${{ github.workspace }}/Utilities/pythontools
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    steps:
      - name: checkout sources
        uses: actions/checkout@master
      - name: compile_xspec
        run: |
          cd ${SPEC_PATH}
          make CC=gfortran xspec
      - name: compile_dspec
        run: |
          cd ${SPEC_PATH}
          make CC=gfortran dspec
      - name: run_fast_cartesian
        run: |
          cd ${SPEC_PATH}/ci/G1V03L2Fi
          echo ${PYTHONPATH}
          mpiexec -n 3 --allow-run-as-root ${SPEC_PATH}/xspec G1V03L2Fi.001.sp
          python3 -m py_spec.ci.test compare.h5 G1V03L2Fi.001.sp.h5 


