# This is a basic workflow to help you get started with Actions

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ try_doxygen ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      LATEX_DOC_DIR: ${{ github.workspace }}/docs/latex
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install doxygen and make
      run: sudo apt-get install perl doxygen doxygen-latex graphviz build-essential
    
    - name: Doxygen Action (based on mattnotmitt/doxygen-action@v1.1.0)
      run: doxygen ./Doxyfile
    
    - name: Make Pdf
      run: cd ./docs/latex && make

    - name: Copy Pdf
      working-directory: ${{ github.workspace }}
      run: cp ./docs/latex/refman.pdf ./docs/html/SPEC_manual.pdf

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Default Doxyfile build documentation to html directory. 
        # Change the directory if changes in Doxyfile
        publish_dir: ./docs/html
