name: python_wrapper
on: [push, pull_request]
jobs:
  python_wrapper-build:
    runs-on: ubuntu-latest
    name: python_wrapper build
    
    steps:
    - uses: actions/checkout@v4

    # Python3 should be pre-installed on 'ubuntu-latest'
    - name: Python version info
      run: |
        python --version
        pip --version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gfortran mpi-default-bin mpi-default-dev libhdf5-103 libhdf5-dev libfftw3-bin libfftw3-dev libopenblas0-openmp libopenblas-dev cmake ninja-build meson
        pip install  numpy f90nml scikit-build scipy
        pip install  git+https://github.com/zhucaoxiang/f90wrap@main_off

    - name: Build python_wrapper
      run: |
        pip install .
        
    - name: Test if installation is ok
      run: |
        python -c "import spec; print('success')"
